[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
ab_token = "D5aNoP8aU9CnWtfCByURp42NEsTdS52GVyB7ufEK3KYS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://virulent-wandering-reel.solana-devnet.quiknode.pro/c29fc55807faf8297c2fed73d3cd98150fd970ad/"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
