[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
ab_token = "7vfAZgrKyYV2e3XTKuwisXfVcdSY7vMZ7N5m6ppNMboP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.mainnet-beta.solana.com"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
